import argparse
import time
import copy
import sys
import os
from contextlib import redirect_stdout
from naive import CYK_graph as naive_CYK
from fast import CYK_graph as fast_CYK
from faster import CYK_graph as faster_CYK

graph1 = [
    ["0", "a", "0", "0", "0"],
    ["0", "0", "d", "0", "0"],
    ["0", "0", "0", "d", "0"],
    ["0", "0", "0", "0", "c"],
    ["0", "0", "0", "0", "0"],
]

graph2 = [
    ["0", "a", "0", "0", "0"],
    ["0", "0", "d", "0", "0"],
    ["0", "0", "0", "d", "0"],
    ["0", "0", "0", "c", "c"],
    ["0", "0", "0", "0", "0"],
]


def test_correctness(use_weak):
    print("Testing correctness...")
    for i, graph in enumerate([graph1, graph2], 1):
        naive_result = copy.deepcopy(graph)
        fast_result = copy.deepcopy(graph)
        faster_result = copy.deepcopy(graph)

        naive_CYK(naive_result, log=False)
        fast_CYK(fast_result, log=False)
        faster_CYK(faster_result, log=False)

        # Sort inner lists for consistent comparison
        for row in naive_result:
            for cell in row:
                cell.sort()
        for row in fast_result:
            for cell in row:
                cell.sort()
        for row in faster_result:
            for cell in row:
                cell.sort()

        l = len(naive_result) - 1
        weak_naive_result = naive_result[0][l]
        weak_fast_result = fast_result[0][l]
        weak_faster_result = faster_result[0][l]

        if use_weak:
            if weak_naive_result == weak_fast_result:
                print(f"Test {i}-fast:   PASS - Results match")
            else:
                print(f"Test {i}-fast:   FAIL - Results differ")
                print("Naive:", weak_naive_result)
                print("Fast:", weak_fast_result)

            if weak_naive_result == weak_faster_result:
                print(f"Test {i}-faster: PASS - Results match")
            else:
                print(f"Test {i}-faster: FAIL - Results differ")
                print("Naive:", weak_naive_result)
                print("Faster:", weak_faster_result)
        else:
            if naive_result == fast_result:
                print(f"Test {i}-fast:   PASS - Results match")
            else:
                print(f"Test {i}-fast:   FAIL - Results differ")
                print("Naive:", naive_result)
                print("Fast:", fast_result)

            if naive_result == faster_result:
                print(f"Test {i}-faster: PASS - Results match")
            else:
                print(f"Test {i}-faster: FAIL - Results differ")
                print("Naive:", naive_result)
                print("Faster:", faster_result)


N = 1000


def test_performance():
    print("\nTesting performance on small graph (n=5)...")
    graph = graph1
    start = time.time()
    with redirect_stdout(open(os.devnull, "w")):
        for _ in range(N):
            test_graph = copy.deepcopy(graph)
            naive_CYK(test_graph, log=False)
    naive_time = time.time() - start

    start = time.time()
    for _ in range(N):
        test_graph = copy.deepcopy(graph)
        fast_CYK(test_graph, log=False)
    fast_time = time.time() - start

    start = time.time()
    for _ in range(N):
        test_graph = copy.deepcopy(graph)
        faster_CYK(test_graph, log=False)
    faster_time = time.time() - start

    print(
        f"Naive: {naive_time:.4f}s, Fast:   {fast_time:.4f}s, Speedup: {naive_time / fast_time:.2f}x"
    )

    print(
        f"Naive: {naive_time:.4f}s, Faster: {faster_time:.4f}s, Speedup: {naive_time / faster_time:.2f}x"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test CYK")
    parser.add_argument("--weak", action="store_true", help="Only compare if word is generated by grammar")
    args = parser.parse_args()

    test_correctness(args.weak)
    test_performance()
